local: &DEFUALT
  data_path: /home/tldr/Projects/models/current/VAE-LSTM/data/processed/train.tfrecord
  eval_path: /home/tldr/Projects/models/current/VAE-LSTM/data/processed/val.tfrecord
  vocab_path: /home/tldr/Projects/models/current/VAE-LSTM/data/processed/vocab.tsv
  embed_path: /home/tldr/Projects/models/current/VAE-LSTM/data/external/crawl-300d-2M.vec
  model_dir: /home/tldr/Projects/models/current/VAE-LSTM/results/
  debug: False


